// import './Wildlife.css'

const Culture = () => {
    return ( 
    <div className='container'>
      <h1>Kenyan Communities</h1>
                <hr></hr>
                <h2 className="text-center">Culturally Vibrant, Beautifully Diverse</h2>
                <hr></hr>
                <p>Kenya — home to more than 40 different ethnic groups — boasts of both cultural and natural diversity. If you were to travel across the country, you’d see the Indian Ocean, towering mountains and vast savannas. You’d hear 60 different languages. You’d taste the unique flavors of the many different styles of Kenyan food. It is a truly diverse and vibrant country. </p>
                <a href="https://blog.compassion.com/facts-about-kenya/">Click for more</a>
    <div>
        <h1>Kenyan Tribes</h1>

        <img id="img2" src="https://i.pinimg.com/564x/eb/1e/b6/eb1eb61d51f963e12899e90487b9212b.jpg" alt=""/>
        <img id="img1" src="https://i.pinimg.com/564x/d2/d8/e8/d2d8e8a4ece17cdd70e6fd7199762a02.jpg" alt=""/>

        <p>The idea that Kenya is made up of 42(+) tribes is widespread,
             {/* but the origins, nature and consequences of any list are not well-known. This article compares ethnic classifications in all Kenyan censuses to demonstrate the origins of the ‘42’ in (only) the 1969 census, and the multiple political purposes of classifying and counting. To make sense of why the 42(+) remains significant, I argue a cultivated vagueness provides a sense of consistency, linking a national past to present and future, while providing the basis for both numbers-based competitive politics and more inclusive politics. Moreover, it avoids engaging in politically risky work of making legible sense of shifts in ethnic identities, classifications and numbers, and avoids having to resolve their relation to the nation, which benefits both state and citizens. Extending literature on the political utility of uncertainty, I theorise this cultivated vagueness as magic, backed by opaque forces, potentially dangerous or beneficent, which deters interrogation or certainty on all sides. To further clarify this awkward relationship between vagueness and certainty, I argue ethnic classifications are intelligible via the social imaginary of the 42(+), but not especially legible, contesting the literature on census practices as tools of legibility and governability.</p> */}
        {/* <h1>Black rhinoceros</h1> */}
        </p>
        <p>It was a hot and dusty day in January 2019. Sam had been driving me around Nairobi since my first visit, ten years earlier. I often float ideas past him as we endure interminable traffic. ‘Sam, how many tribes are there in Kenya?’ I knew there was no definitive answer but I wanted to know his thoughts. ‘Well, now we are … is it … 46? Or 47? We used to be 42 but some new ones were recently added. Makondes. Asians. Who else was it? Nubians … ’. ‘And where is the list?’ I probed. ‘Oh that one … is it gazetted somewhere? I don’t know.’ Later that day, while he refined my left hook, I asked my boxing trainer, Jeff. Embarrassed, he laughed and said ‘You know … I’ve not brushed up on my tribes lately … .’ ‘Just roughly … how many?’ He replied after some thought, ‘I think … well … I know that we used to be … is it 41? Or 42? 42.
             We used to be 42. But now, I don’t know.’ In multiple interviews with various government officials, I was repeatedly told there were 42+ tribes, but nobody could tell me the nature or location of the list. ‘Do you know?’ one official asked me. Ten years earlier, I asked members of the minority Nubian community too: ‘Forty-two tribes. And we will be the 43rd’. They even had a letter from a Minister declaring they would, indeed, be counted as such in the 2009 census.1 But I struggled to find the list. Who is on it? Does it even exist? And if so, who controls it, and how? Why does nobody know? And does it matter?
        </p>
        <img id="img2" src="https://i.pinimg.com/564x/5e/f5/86/5ef586fec26fa20eff92c206bc320d9f.jpg" alt=""/>
        <img id="img1" src="https://i.pinimg.com/564x/e4/39/46/e43946548c6e1ac7c17ce85f36a7aca0.jpg" alt=""/>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium expedita facere doloribus sint illo, minus, explicabo eius quam eaque eos error est nulla. Facilis ratione nesciunt fugiat ipsa, aut quam odio eaque architecto corrupti sapiente consectetur laborum possimus culpa voluptate. Iure in placeat voluptate nihil quam voluptatem asperiores omnis, aliquid reiciendis, aliquam praesentium, ab beatae. Voluptate voluptas dolor earum, fugit aperiam totam ipsam incidunt animi aliquam? Atque ut expedita iure culpa explicabo cupiditate laborum reiciendis doloribus repellat recusandae. At sunt, iusto consequatur cumque veritatis debitis alias incidunt esse? Labore asperiores alias deleniti consequatur dolores quidem sit accusantium nemo earum minus non reprehenderit, necessitatibus nam. Enim, aspernatur, veritatis sunt quia expedita assumenda vitae pariatur itaque eveniet ad dignissimos? Voluptatum, neque. Consequuntur perferendis placeat quis earum, officiis repellat, fugit reprehenderit aut iusto minus nemo quas sed quia quae dolore neque cupiditate, expedita distinctio. Asperiores obcaecati, quidem facilis beatae accusamus aliquid enim veritatis harum, tempore autem magni sint modi voluptates perspiciatis itaque voluptate voluptatem! Tempora quia ad vero quos in ex, id doloribus labore totam cupiditate alias. Magnam minima nemo deleniti provident iure dolorem ipsa maxime architecto. Consequatur distinctio, illum fugiat suscipit repellendus exercitationem, dolorum voluptatum rerum tenetur dignissimos repellat officiis nostrum velit.</p>
        <br></br>
        <h1>Food</h1>
        <img id="img1" src="https://i.pinimg.com/236x/ae/26/9f/ae269f15d94f8c53a13d9f52419cf40e.jpg" alt="" />
        <img id="img2" src="https://i.pinimg.com/564x/4e/47/4e/4e474e30abed551d04062acf64beae29.jpg" alt="" />
        <p>From the bustling city centre of Nairobi to the port and beaches of Mombasa, Kenyan cuisine reflects the diversity of its people and its various cultural influences stemming back to the Indian Ocean trade. Whether it’s traditional nyama choma (meat roasted over charcoal) served with ugali (maize-meal cake), seafood with exotic spices, or hot Indian curries, the local cuisine is varied and full of flavour. Here are 10 great Kenyan restaurants, each reflecting a part of the country’s rich food and culinary culture.</p>
        <p>Serving a superb blend of Asian, Middle Eastern, French and Italian cuisine, the Talisman Restaurant is a favorite dining spot in downtown Nairobi. The restaurant’s chefs whip up a wonderful selection of fine dishes from scratch using freshly sourced fish from Lamu. Offering 20 different international wines by the glass and a large malt whiskey selection, Talisman also crafts some decadent cocktails. Try the Double Dawas or the award-winning Super Striker for a pleasant surprise. The Talisman features carved wooden pillars, gorgeous tapestries and striking African art, as well as a charming garden full of fig trees and bombax, providing a stylish yet relaxed setting. With live entertainment on selected nights, a visit to the Talisman promises a truly memorable dining experience.</p>
        <img id="img1" src="https://i.pinimg.com/564x/90/85/24/908524b74b214f138a28fd23d65ba69b.jpg" alt="" />
        <img id="img2" src="https://i.pinimg.com/564x/e9/b2/b1/e9b2b1141f589093426733da195d8d3b.jpg" alt="" />
        <p>True to its name, it is of no surprise that meat lovers flock to The Carnivore, an open-air meat speciality restaurant situated just outside Nairobi’s busy city centre. From beef, chicken and ostrich on one end to more exotic dishes of crocodile and camel, the meat is grill-roasted and carved at the table. The buffet option includes an array of tantalising house sauces, soups and desserts. The Carnivore also houses an informal à la carte restaurant during the day that turns into a popular nightclub called Simba Saloon. Set out in a lovely tropical garden with typically African decor, the Carnivore promises an all-you-can-eat feast, matched with impeccable service with a smile, however, at a price. Coupled with traditional dance performances and live music, the Carnivore is simply an extremely seductive option.</p>
        <p>The Open House is one of the best and beloved Indian restaurants in Nairobi. Catering for mild palates to experienced chilli fanatics, the restaurant dishes are authentic, full of distinct flavours and aromatic spices, transporting its diners across the ocean to the heart of India. Dishes include tandoori chicken, mutton biryani, fish tikka masala and an extensive number of traditional vegetarian dishes, all served with aromatic homemade Indian bread. After a spicy meal, try the house special dessert of kulfi badam pista, a heavenly frozen delight made from milk thickened with khoya, chopped almonds and pistachios. Apart from a series of colourful paintings decorating the walls, the Indian-themed décor is simple and tidy, keeping the restaurant’s full focus on its splendid food offering.</p>
       
        <h1>Leopard</h1>
        <img id="img2" src="https://i.pinimg.com/236x/8f/ca/29/8fca292a87dfe712f11225cc1dc3498d.jpg" alt=""/>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium expedita facere doloribus sint illo, minus, explicabo eius quam eaque eos error est nulla. Facilis ratione nesciunt fugiat ipsa, aut quam odio eaque architecto corrupti sapiente consectetur laborum possimus culpa voluptate. Iure in placeat voluptate nihil quam voluptatem asperiores omnis, aliquid reiciendis, aliquam praesentium, ab beatae. Voluptate voluptas dolor earum, fugit aperiam totam ipsam incidunt animi aliquam? Atque ut expedita iure culpa explicabo cupiditate laborum reiciendis doloribus repellat recusandae. At sunt, iusto consequatur cumque veritatis debitis alias incidunt esse? Labore asperiores alias deleniti consequatur dolores quidem sit accusantium nemo earum minus non reprehenderit, necessitatibus nam. Enim, aspernatur, veritatis sunt quia expedita assumenda vitae pariatur itaque eveniet ad dignissimos? Voluptatum, neque. Consequuntur perferendis placeat quis earum, officiis repellat, fugit reprehenderit aut iusto minus nemo quas sed quia quae dolore neque cupiditate, expedita distinctio. Asperiores obcaecati, quidem facilis beatae accusamus aliquid enim veritatis harum, tempore autem magni sint modi voluptates perspiciatis itaque voluptate voluptatem! Tempora quia ad vero quos in ex, id doloribus labore totam cupiditate alias. Magnam minima nemo deleniti provident iure dolorem ipsa maxime architecto. Consequatur distinctio, illum fugiat suscipit repellendus exercitationem, dolorum voluptatum rerum tenetur dignissimos repellat officiis nostrum velit.</p>
        <h1>Wild Beast</h1>
        <img id="img1" src="https://i.pinimg.com/564x/6c/34/47/6c34471717f1c4a4948967c04cf38842.jpg" alt="" />
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium expedita facere doloribus sint illo, minus, explicabo eius quam eaque eos error est nulla. Facilis ratione nesciunt fugiat ipsa, aut quam odio eaque architecto corrupti sapiente consectetur laborum possimus culpa voluptate. Iure in placeat voluptate nihil quam voluptatem asperiores omnis, aliquid reiciendis, aliquam praesentium, ab beatae. Voluptate voluptas dolor earum, fugit aperiam totam ipsam incidunt animi aliquam? Atque ut expedita iure culpa explicabo cupiditate laborum reiciendis doloribus repellat recusandae. At sunt, iusto consequatur cumque veritatis debitis alias incidunt esse? Labore asperiores alias deleniti consequatur dolores quidem sit accusantium nemo earum minus non reprehenderit, necessitatibus nam. Enim, aspernatur, veritatis sunt quia expedita assumenda vitae pariatur itaque eveniet ad dignissimos? Voluptatum, neque. Consequuntur perferendis placeat quis earum, officiis repellat, fugit reprehenderit aut iusto minus nemo quas sed quia quae dolore neque cupiditate, expedita distinctio. Asperiores obcaecati, quidem facilis beatae accusamus aliquid enim veritatis harum, tempore autem magni sint modi voluptates perspiciatis itaque voluptate voluptatem! Tempora quia ad vero quos in ex, id doloribus labore totam cupiditate alias. Magnam minima nemo deleniti provident iure dolorem ipsa maxime architecto. Consequatur distinctio, illum fugiat suscipit repellendus exercitationem, dolorum voluptatum rerum tenetur dignissimos repellat officiis nostrum velit.</p>
        <h1>Zebra</h1>
        <img id="img2" src="https://i.pinimg.com/564x/76/46/6e/76466ea092ecc98e59612c951ad17e0e.jpg" alt=""/>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium expedita facere doloribus sint illo, minus, explicabo eius quam eaque eos error est nulla. Facilis ratione nesciunt fugiat ipsa, aut quam odio eaque architecto corrupti sapiente consectetur laborum possimus culpa voluptate. Iure in placeat voluptate nihil quam voluptatem asperiores omnis, aliquid reiciendis, aliquam praesentium, ab beatae. Voluptate voluptas dolor earum, fugit aperiam totam ipsam incidunt animi aliquam? Atque ut expedita iure culpa explicabo cupiditate laborum reiciendis doloribus repellat recusandae. At sunt, iusto consequatur cumque veritatis debitis alias incidunt esse? Labore asperiores alias deleniti consequatur dolores quidem sit accusantium nemo earum minus non reprehenderit, necessitatibus nam. Enim, aspernatur, veritatis sunt quia expedita assumenda vitae pariatur itaque eveniet ad dignissimos? Voluptatum, neque. Consequuntur perferendis placeat quis earum, officiis repellat, fugit reprehenderit aut iusto minus nemo quas sed quia quae dolore neque cupiditate, expedita distinctio. Asperiores obcaecati, quidem facilis beatae accusamus aliquid enim veritatis harum, tempore autem magni sint modi voluptates perspiciatis itaque voluptate voluptatem! Tempora quia ad vero quos in ex, id doloribus labore totam cupiditate alias. Magnam minima nemo deleniti provident iure dolorem ipsa maxime architecto. Consequatur distinctio, illum fugiat suscipit repellendus exercitationem, dolorum voluptatum rerum tenetur dignissimos repellat officiis nostrum velit.</p>
        
   
        <h1>Black rhinoceros</h1>
        <img id="img1" src="https://i.pinimg.com/236x/55/5f/30/555f300947390c51bca21a68262a74d5.jpg" alt="" />
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium expedita facere doloribus sint illo, minus, explicabo eius quam eaque eos error est nulla. Facilis ratione nesciunt fugiat ipsa, aut quam odio eaque architecto corrupti sapiente consectetur laborum possimus culpa voluptate. Iure in placeat voluptate nihil quam voluptatem asperiores omnis, aliquid reiciendis, aliquam praesentium, ab beatae. Voluptate voluptas dolor earum, fugit aperiam totam ipsam incidunt animi aliquam? Atque ut expedita iure culpa explicabo cupiditate laborum reiciendis doloribus repellat recusandae. At sunt, iusto consequatur cumque veritatis debitis alias incidunt esse? Labore asperiores alias deleniti consequatur dolores quidem sit accusantium nemo earum minus non reprehenderit, necessitatibus nam. Enim, aspernatur, veritatis sunt quia expedita assumenda vitae pariatur itaque eveniet ad dignissimos? Voluptatum, neque. Consequuntur perferendis placeat quis earum, officiis repellat, fugit reprehenderit aut iusto minus nemo quas sed quia quae dolore neque cupiditate, expedita distinctio. Asperiores obcaecati, quidem facilis beatae accusamus aliquid enim veritatis harum, tempore autem magni sint modi voluptates perspiciatis itaque voluptate voluptatem! Tempora quia ad vero quos in ex, id doloribus labore totam cupiditate alias. Magnam minima nemo deleniti provident iure dolorem ipsa maxime architecto. Consequatur distinctio, illum fugiat suscipit repellendus exercitationem, dolorum voluptatum rerum tenetur dignissimos repellat officiis nostrum velit.</p>
        <h1>Leopard</h1>
        <img id="img2" src="https://i.pinimg.com/236x/8f/ca/29/8fca292a87dfe712f11225cc1dc3498d.jpg" alt=""/>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium expedita facere doloribus sint illo, minus, explicabo eius quam eaque eos error est nulla. Facilis ratione nesciunt fugiat ipsa, aut quam odio eaque architecto corrupti sapiente consectetur laborum possimus culpa voluptate. Iure in placeat voluptate nihil quam voluptatem asperiores omnis, aliquid reiciendis, aliquam praesentium, ab beatae. Voluptate voluptas dolor earum, fugit aperiam totam ipsam incidunt animi aliquam? Atque ut expedita iure culpa explicabo cupiditate laborum reiciendis doloribus repellat recusandae. At sunt, iusto consequatur cumque veritatis debitis alias incidunt esse? Labore asperiores alias deleniti consequatur dolores quidem sit accusantium nemo earum minus non reprehenderit, necessitatibus nam. Enim, aspernatur, veritatis sunt quia expedita assumenda vitae pariatur itaque eveniet ad dignissimos? Voluptatum, neque. Consequuntur perferendis placeat quis earum, officiis repellat, fugit reprehenderit aut iusto minus nemo quas sed quia quae dolore neque cupiditate, expedita distinctio. Asperiores obcaecati, quidem facilis beatae accusamus aliquid enim veritatis harum, tempore autem magni sint modi voluptates perspiciatis itaque voluptate voluptatem! Tempora quia ad vero quos in ex, id doloribus labore totam cupiditate alias. Magnam minima nemo deleniti provident iure dolorem ipsa maxime architecto. Consequatur distinctio, illum fugiat suscipit repellendus exercitationem, dolorum voluptatum rerum tenetur dignissimos repellat officiis nostrum velit.</p>
        <h1>Wild Beast</h1>
        <img id="img1" src="https://i.pinimg.com/564x/6c/34/47/6c34471717f1c4a4948967c04cf38842.jpg" alt="" />
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium expedita facere doloribus sint illo, minus, explicabo eius quam eaque eos error est nulla. Facilis ratione nesciunt fugiat ipsa, aut quam odio eaque architecto corrupti sapiente consectetur laborum possimus culpa voluptate. Iure in placeat voluptate nihil quam voluptatem asperiores omnis, aliquid reiciendis, aliquam praesentium, ab beatae. Voluptate voluptas dolor earum, fugit aperiam totam ipsam incidunt animi aliquam? Atque ut expedita iure culpa explicabo cupiditate laborum reiciendis doloribus repellat recusandae. At sunt, iusto consequatur cumque veritatis debitis alias incidunt esse? Labore asperiores alias deleniti consequatur dolores quidem sit accusantium nemo earum minus non reprehenderit, necessitatibus nam. Enim, aspernatur, veritatis sunt quia expedita assumenda vitae pariatur itaque eveniet ad dignissimos? Voluptatum, neque. Consequuntur perferendis placeat quis earum, officiis repellat, fugit reprehenderit aut iusto minus nemo quas sed quia quae dolore neque cupiditate, expedita distinctio. Asperiores obcaecati, quidem facilis beatae accusamus aliquid enim veritatis harum, tempore autem magni sint modi voluptates perspiciatis itaque voluptate voluptatem! Tempora quia ad vero quos in ex, id doloribus labore totam cupiditate alias. Magnam minima nemo deleniti provident iure dolorem ipsa maxime architecto. Consequatur distinctio, illum fugiat suscipit repellendus exercitationem, dolorum voluptatum rerum tenetur dignissimos repellat officiis nostrum velit.</p>
        <h1>Zebra</h1>
        <img id="img2" src="https://i.pinimg.com/564x/76/46/6e/76466ea092ecc98e59612c951ad17e0e.jpg" alt=""/>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium expedita facere doloribus sint illo, minus, explicabo eius quam eaque eos error est nulla. Facilis ratione nesciunt fugiat ipsa, aut quam odio eaque architecto corrupti sapiente consectetur laborum possimus culpa voluptate. Iure in placeat voluptate nihil quam voluptatem asperiores omnis, aliquid reiciendis, aliquam praesentium, ab beatae. Voluptate voluptas dolor earum, fugit aperiam totam ipsam incidunt animi aliquam? Atque ut expedita iure culpa explicabo cupiditate laborum reiciendis doloribus repellat recusandae. At sunt, iusto consequatur cumque veritatis debitis alias incidunt esse? Labore asperiores alias deleniti consequatur dolores quidem sit accusantium nemo earum minus non reprehenderit, necessitatibus nam. Enim, aspernatur, veritatis sunt quia expedita assumenda vitae pariatur itaque eveniet ad dignissimos? Voluptatum, neque. Consequuntur perferendis placeat quis earum, officiis repellat, fugit reprehenderit aut iusto minus nemo quas sed quia quae dolore neque cupiditate, expedita distinctio. Asperiores obcaecati, quidem facilis beatae accusamus aliquid enim veritatis harum, tempore autem magni sint modi voluptates perspiciatis itaque voluptate voluptatem! Tempora quia ad vero quos in ex, id doloribus labore totam cupiditate alias. Magnam minima nemo deleniti provident iure dolorem ipsa maxime architecto. Consequatur distinctio, illum fugiat suscipit repellendus exercitationem, dolorum voluptatum rerum tenetur dignissimos repellat officiis nostrum velit.</p>
        
</div>
    </div>     

         );
}
 
export default Culture;
{/* <button  className='card-btn'>
Visit <span>&rarr;</span>
</button> */}